version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Check Node 12...
      - node -v
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install -g gatsby-cli
      - gatsby -v
      - npm install
      - echo Fixing audit.
      - npm audit fix --force
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: public
